runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11"

resources:
  cpu: 1
  memory_gb: 6.1
  disk_size_gb: 18

readiness_check:
  app_start_timeout_sec: 900 